default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: development_picha
  username: saumya
  password: <%= ENV['PICHA_DATABASE_PASSWORD'] %>
  port: 5432

test:
  <<: *default
  database: test_picha